INCLUDES = -I..
CFLAGS += -Wall -Wextra -Os -Wl,-S -Wl,-x -Wl,-dead_strip
LDFLAGS += -lobjc -framework CoreFoundation -framework Foundation
LDFLAGS_IMAGE += -framework AppKit
LDFLAGS_AUDIO += -framework AudioToolbox -framework AudioUnit -framework CoreServices -Wl,-dead_strip_dylibs

all:
	$(CC) $(INCLUDES) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_IMAGE) test_oswrapper_image.c -o test_oswrapper_image
	$(CC) $(INCLUDES) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_AUDIO) test_oswrapper_audio.c -o test_oswrapper_audio
	$(CC) $(INCLUDES) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_AUDIO) demo_oswrapper_audio_mac.c -o demo_oswrapper_audio_mac

clean:
	rm -f test_oswrapper_image test_oswrapper_audio demo_oswrapper_audio_mac
