name: Build on push or pull request

on: [ push, pull_request ]

jobs:
  build_macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build examples
        working-directory: test
        run: make -f Makefile.osx
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Examples-macOS
          path: |
            test/test_oswrapper_image
            test/test_oswrapper_audio
            test/demo_oswrapper_audio_mac
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build examples
        working-directory: test
        run: nmake -f Makefile.win32
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Examples-windows
          path: |
            test/test_oswrapper_image.exe
            test/test_oswrapper_image_no_crt.exe
            test/test_oswrapper_audio.exe
            test/test_oswrapper_audio_no_crt.exe
  build_emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.35
          actions-cache-folder: 'emsdk-cache'
      - name: Build examples
        working-directory: test
        run: make -f Makefile.em
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Examples-Emscripten
          path: |
            test/test_oswrapper_image.html
            test/test_oswrapper_image.js
            test/test_oswrapper_image.wasm
